### ISSUE TITLE
User profile view results in stack trace when Sufia.config.arkivo_api is false

### ISSUE THREAD

**Issue by kerchner** [projecthydra/sufia#1235]
We are running an instance where Zotero integration is not (yet) set up.  Clicking on any user profile leads to the following stack trace:

```
Showing /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/sufia-6.1.0/app/views/users/_user_info.html.erb where line #8 raised:

undefined method `zotero_userid' for #<User:0x007fd7b6f11c48>

Extracted source (around line #433):

      else
        match = match_attribute_method?(method.to_s)
        match ? attribute_missing(match, *args, &block) : super
      end
    end


Trace of template inclusion: /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/sufia-6.1.0/app/views/users/_profile.html.erb, /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/sufia-6.1.0/app/views/users/_profile_tabs.html.erb, /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/sufia-6.1.0/app/views/users/show.html.erb
```

See conversation thread at:
 https://github.com/projecthydra/sufia/commit/286eb0786a9047aac036388f1bb9c77e73b15700
and solution recommended by @mgiarlo and successfully applied here:
 https://github.com/gwu-libraries/scholarspace/issues/10

**Comment by mjgiarlo** [comment]
Pull request #1237 created. Once merged, I can work on a 6.1.1 release.  Thanks, @kerchner!

**Comment by mjgiarlo** [comment]
The 6.2.0 release is now out. Upgrade at will and you can remove your workaround, @kerchner.  Thanks again for letting us know about this.
